name: MAIN -- CHECKING SEMI-AUTO TAG
on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: TissueImageAnalytics/tiatoolbox
  image: ghcr.io/tissueimageanalytics/tiatoolbox
  TOOLBOX_VER: 1.3.0

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - dockerfile: ./3.7/Debian/Dockerfile
            mtag: py3.7-debian
            tag: "${{ env.image }}:${{ env.TOOLBOX_VER }}-${{ matrix.mtag }}"
          - dockerfile: ./3.8/Debian/Dockerfile
            mtag: py3.8-debian
            tag: "${{ env.image }}:${{ env.TOOLBOX_VER }}-${{ matrix.mtag }}"
          - dockerfile: ./3.9/Debian/Dockerfile
            mtag: py3.9-debian
            tag: "${{ env.image }}:${{ env.TOOLBOX_VER }}-${{ matrix.mtag }}"
          - dockerfile: ./3.9/Ubuntu/Dockerfile
            mtag: py3.9-ubuntu
            tag: "${{ env.image }}:${{ env.TOOLBOX_VER }}-${{ matrix.mtag }}"
          - dockerfile: ./3.9/Ubuntu/Dockerfile
            mtag: latest
            tag: "${{ matrix.mtag }}"
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.image }}
          tags: |
              type=ref,event=branch
              type=ref,event=pr
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}
      - name: CHECKING TAGS
        run: echo "${{ env.tag }}"
